apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.DOMAIN }}
        - --provider={{ .Values.PROVIDER }}
        - --registry=txt
        - --txt-owner-id={{ .Values.DOMAIN }}
        - --log-level=info
        - --interval=1m
        volumeMounts:
        - mountPath: /usr/share/zoneinfo
          name: hostpath
      volumes:
      - name: hostpath
        hostPath:
          path: /usr/share/zoneinfo
          type: Directory          
