apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

generatorOptions:
  disableNameSuffixHash: true

bases:
- ../../base

resources:
- ns.yaml

patchesStrategicMerge:
- external-dns-deployment.yaml

transformers:
- helm.yaml
